INSERT INTO pacerscraper_pacerbankruptcyparty (id, party_name, party_type, bankruptcy_index_case_id) VALUES (1, 'Michele A. Gerondeau', 'Defendant', 1390);
INSERT INTO pacerscraper_pacerbankruptcyparty (id, party_name, party_type, bankruptcy_index_case_id) VALUES (2, 'Johann Luzcando', 'Plaintiff', 1390);
INSERT INTO pacerscraper_pacerbankruptcyparty (id, party_name, party_type, bankruptcy_index_case_id) VALUES (3, 'Beth Scholten', 'Plaintiff', 1390);
INSERT INTO pacerscraper_pacerbankruptcyparty (id, party_name, party_type, bankruptcy_index_case_id) VALUES (4, 'Robyn B. Bernstein', 'Plaintiff', 1391);
INSERT INTO pacerscraper_pacerbankruptcyparty (id, party_name, party_type, bankruptcy_index_case_id) VALUES (5, 'United States Of America - IRS', 'Defendant', 1391);
INSERT INTO pacerscraper_pacerbankruptcyparty (id, party_name, party_type, bankruptcy_index_case_id) VALUES (6, ' ', 'not parsed', 1391);
INSERT INTO pacerscraper_pacerbankruptcyparty (id, party_name, party_type, bankruptcy_index_case_id) VALUES (7, 'John Does 1-10', 'Defendant', 1392);
INSERT INTO pacerscraper_pacerbankruptcyparty (id, party_name, party_type, bankruptcy_index_case_id) VALUES (8, 'Ji Soon Jang', 'Defendant', 1392);
INSERT INTO pacerscraper_pacerbankruptcyparty (id, party_name, party_type, bankruptcy_index_case_id) VALUES (9, ' ', 'not parsed', 1392);
INSERT INTO pacerscraper_pacerbankruptcyparty (id, party_name, party_type, bankruptcy_index_case_id) VALUES (10, 'Soon R Jang', 'Defendant', 1392);
INSERT INTO pacerscraper_pacerbankruptcyparty (id, party_name, party_type, bankruptcy_index_case_id) VALUES (11, ' ', 'not parsed', 1392);
INSERT INTO pacerscraper_pacerbankruptcyparty (id, party_name, party_type, bankruptcy_index_case_id) VALUES (12, 'Woody Jang', 'Defendant', 1392);
INSERT INTO pacerscraper_pacerbankruptcyparty (id, party_name, party_type, bankruptcy_index_case_id) VALUES (13, ' ', 'not parsed', 1392);
INSERT INTO pacerscraper_pacerbankruptcyparty (id, party_name, party_type, bankruptcy_index_case_id) VALUES (14, 'Montclair Pizza House, Inc.', 'Defendant', 1392);
INSERT INTO pacerscraper_pacerbankruptcyparty (id, party_name, party_type, bankruptcy_index_case_id) VALUES (15, 'Eric Perkins', 'Plaintiff', 1392);
INSERT INTO pacerscraper_pacerbankruptcyparty (id, party_name, party_type, bankruptcy_index_case_id) VALUES (16, 'Lourdes Cardiology Services, PC', 'Defendant', 1393);
INSERT INTO pacerscraper_pacerbankruptcyparty (id, party_name, party_type, bankruptcy_index_case_id) VALUES (17, 'Louis A. Macri', 'Plaintiff', 1393);
INSERT INTO pacerscraper_pacerbankruptcyparty (id, party_name, party_type, bankruptcy_index_case_id) VALUES (18, 'Nancy Isaacson', 'Plaintiff', 1394);
INSERT INTO pacerscraper_pacerbankruptcyparty (id, party_name, party_type, bankruptcy_index_case_id) VALUES (19, 'Lake Congers Road LLC', 'Defendant', 1394);
INSERT INTO pacerscraper_pacerbankruptcyparty (id, party_name, party_type, bankruptcy_index_case_id) VALUES (20, 'Mehran Mehrnia', 'Defendant', 1394);
