# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-22 02:10


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacerscraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacerJudgmentIndexCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50)),
                ('in_favor', models.CharField(max_length=100)),
                ('against', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('judgment_date', models.DateField()),
                ('document', models.IntegerField()),
                ('interest', models.FloatField()),
                ('court_cost', models.FloatField()),
                ('case_status', models.CharField(max_length=50)),
                ('satisfication_date', models.DateField()),
            ],
        ),
    ]
