# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-29 17:46


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacerscraper', '0005_auto_20171028_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacerjudgmentindexcase',
            name='alias_file',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pacerjudgmentindexcase',
            name='case_number',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pacerjudgmentindexcase',
            name='case_summary_file',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pacerjudgmentindexcase',
            name='party_file',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
