# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-10 22:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacerscraper', '0006_auto_20171029_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankruptcyIndexReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('archive_file', models.CharField(max_length=255)),
            ],
        ),
    ]
