# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-11 01:00


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacerscraper', '0007_bankruptcyindexreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacerBankruptcyIndexCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(db_index=True, max_length=255)),
                ('case_title', models.CharField(max_length=255)),
                ('chapter_lead_bk_case', models.CharField(max_length=255)),
                ('date_filed', models.DateField()),
                ('date_closed', models.DateField()),
                ('alias_file', models.CharField(db_index=True, max_length=255)),
                ('case_summary_file', models.CharField(db_index=True, max_length=255)),
                ('party_file', models.CharField(db_index=True, max_length=255)),
                ('bankruptcy_index_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacerscraper.BankruptcyIndexReport')),
            ],
        ),
    ]
