# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-24 15:42


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacerscraper', '0009_auto_20171112_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacerBankruptcyParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(db_index=True, max_length=255)),
                ('party_type', models.CharField(max_length=50)),
                ('bankruptcy_index_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacerscraper.PacerBankruptcyIndexCase')),
            ],
        ),
    ]
