# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-06 22:08


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacerscraper', '0012_auto_20180106_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacerjudgmentindexcase',
            name='alias_file_processed',
        ),
        migrations.AddField(
            model_name='pacerbankruptcyindexcase',
            name='alias_file_processed',
            field=models.CharField(db_index=True, default='N', max_length=1),
        ),
    ]
