# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-20 15:49


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacerscraper', '0019_auto_20180421_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScnjDebtorDob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
