# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-20 23:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacerscraper', '0020_scnjdebtordob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scnjdebtordob',
            name='dob',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
