# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-29 02:41


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacerscraper', '0021_auto_20191020_1942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScnjDebtorDob',
        ),
    ]
