# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-27 22:41


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacerscraper', '0023_bankruptcyindexreport_1_bankruptcyindexreport_2_bankruptcyindexreport_3_bankruptcyindexreport_4_pace'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankruptcyIndexReport_5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('archive_file', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pacerscraper_bankruptcyindexreport_5',
            },
        ),
        migrations.CreateModel(
            name='PacerBankruptcyIndexCase_5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(db_index=True, max_length=255, unique=True)),
                ('case_title', models.CharField(max_length=255)),
                ('chapter_lead_bk_case', models.CharField(max_length=255)),
                ('date_filed', models.DateField()),
                ('date_closed', models.DateField(blank=True, null=True)),
                ('alias_file', models.CharField(db_index=True, max_length=255)),
                ('case_summary_file', models.CharField(db_index=True, max_length=255)),
                ('party_file', models.CharField(db_index=True, max_length=255)),
                ('alias_file_processed', models.CharField(db_index=True, default='N', max_length=1)),
                ('party_file_processed', models.CharField(db_index=True, default='N', max_length=1)),
                ('bankruptcy_index_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacerscraper.BankruptcyIndexReport_4')),
            ],
            options={
                'db_table': 'pacerscraper_pacerbankruptcyindexcase_5',
            },
        ),
        migrations.CreateModel(
            name='PacerBankruptcyParty_5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(db_index=True, max_length=255)),
                ('party_type', models.CharField(db_index=True, max_length=255)),
                ('bankruptcy_index_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacerscraper.PacerBankruptcyIndexCase')),
            ],
            options={
                'db_table': 'pacerscraper_pacerbankruptcyparty_5',
            },
        ),
    ]
