# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-26 17:21


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_processed', models.DateTimeField()),
                ('file_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StateClosingsReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('century_year', models.CharField(max_length=50)),
                ('dckt_jdg_num_yr', models.CharField(max_length=50)),
                ('dckt_jdg_seq_num', models.CharField(max_length=50)),
                ('dckt_jdg_type_code', models.CharField(max_length=50)),
                ('debt_num', models.CharField(max_length=50)),
                ('party_num', models.CharField(max_length=50)),
                ('ptydbt_status_code', models.CharField(max_length=50)),
                ('ptydbt_status_date', models.CharField(max_length=50)),
                ('case_title', models.CharField(max_length=50)),
                ('party_last_name', models.CharField(max_length=50)),
                ('party_first_name', models.CharField(max_length=50)),
                ('party_mid_intl', models.CharField(max_length=50)),
                ('party_cnt', models.CharField(max_length=50)),
                ('party_dbt_cnt', models.CharField(max_length=50)),
                ('partical_close_indicator', models.CharField(max_length=50)),
                ('warrent_of_sat_indicator', models.CharField(max_length=50)),
                ('closing_document_code', models.CharField(max_length=50)),
                ('jptydoc_target', models.CharField(max_length=50)),
                ('venue_id', models.CharField(max_length=50)),
                ('dckt_type_code', models.CharField(max_length=50)),
                ('dckt_seq_num', models.CharField(max_length=50)),
                ('dckt_crt_year', models.CharField(max_length=50)),
                ('nonacms_venue_id', models.CharField(max_length=50)),
                ('nonacms_key_frst', models.CharField(max_length=50)),
                ('nonacms_key_mid', models.CharField(max_length=50)),
                ('nonacms_key_last', models.CharField(max_length=50)),
                ('extract_start_date', models.CharField(max_length=50)),
                ('extract_end_date', models.CharField(max_length=50)),
                ('report_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statereport.ReportBatch')),
            ],
        ),
    ]
