# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-26 21:00


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statereport', '0002_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judgment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=50)),
                ('venue_id', models.CharField(max_length=50)),
                ('court_code', models.CharField(max_length=50)),
                ('report_request_number', models.CharField(max_length=50)),
                ('docketed_judgment_cc', models.CharField(max_length=50)),
                ('docketed_judgment_yy', models.CharField(max_length=50)),
                ('docketed_judgment_seq_num', models.CharField(max_length=50)),
                ('docketed_judgment_type_code', models.CharField(max_length=50)),
                ('debt_number', models.CharField(max_length=50)),
                ('record_type_code_data', models.CharField(max_length=50)),
                ('record_type_code_debt_data', models.CharField(max_length=50)),
                ('docketed_judgment_number_debt_data', models.CharField(max_length=50)),
                ('judgment_number', models.CharField(max_length=50)),
                ('judgment_status_code', models.CharField(max_length=50)),
                ('judgment_status_date', models.CharField(max_length=50)),
                ('judgment_orig_amt', models.CharField(max_length=50)),
                ('judgment_orig_taxed_cost_amt', models.CharField(max_length=50)),
                ('judgment_orig_interest_amt', models.CharField(max_length=50)),
                ('judgment_orig_atty_fee_amt', models.CharField(max_length=50)),
                ('judgment_other_awd_orig_amt', models.CharField(max_length=50)),
                ('judgment_due_amt', models.CharField(max_length=50)),
                ('judgment_due_taxed_cost_amt', models.CharField(max_length=50)),
                ('judgment_due_interest_amt', models.CharField(max_length=50)),
                ('judgment_due_atty_fee_amt', models.CharField(max_length=50)),
                ('judgment_due_other_award_due_amt', models.CharField(max_length=50)),
                ('judgment_time', models.CharField(max_length=50)),
                ('judgment_docketed_date', models.CharField(max_length=50)),
                ('judgment_entered_date', models.CharField(max_length=50)),
                ('judgment_issued_date', models.CharField(max_length=50)),
            ],
        ),
    ]
