# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-26 23:30


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statereport', '0007_auto_20170226_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='statereport.Case'),
        ),
    ]
