# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-27 00:54


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statereport', '0013_auto_20170226_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='party_addt_street_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_city_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_first_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_initial',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_initials',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_last_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_street_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='partyalt',
            name='party_alternate_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='partyalt',
            name='party_first_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='partyalt',
            name='party_initial',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='partyalt',
            name='party_last_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='partyguardian',
            name='guardian_first_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='partyguardian',
            name='guardian_initial',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='partyguardian',
            name='guardian_last_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='partyguardian',
            name='party_first_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='partyguardian',
            name='party_initial',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='partyguardian',
            name='party_last_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stateclosingsreport',
            name='party_first_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stateclosingsreport',
            name='party_last_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stateclosingsreport',
            name='party_mid_intl',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
