# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-20 02:40


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statereport', '0015_debt_party_due_interest_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='jdgcomm_comments',
            field=models.CharField(max_length=75),
        ),
    ]
