# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-06 02:47


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statereport', '0017_auto_20170402_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='docketed_judgment_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
