# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-15 17:05


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statereport', '0019_auto_20180404_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='merged_party_name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
