# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-30 00:39


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statereport', '0022_party_full_search_party_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyalt',
            name='full_search_party_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
