# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-09 00:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statereport', '0025_auto_20181218_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='debt_status_code',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
