# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2021-08-02 00:24


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statereport', '0026_auto_20190108_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtAmountLookup',
            fields=[
                ('debt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='statereport.Debt')),
                ('party_orig_amt', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'debt_amount_lookup',
                'managed': False,
            },
        ),
    ]

# delimiter #
# create trigger ins_orig_amt AFTER INSERT ON statereport_debt
#     FOR EACH ROW
#     BEGIN
#     insert into debt_amount_lookup(debt_id, party_orig_amt, case_id)
#         (
#             select id, cast(substring(party_orig_amt, 1, 9) as unsigned), case_id
#             from statereport_debt
#         );
#     end#
# delimiter ;
