# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2022-05-01 21:24


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statereport', '0027_debtamountlookup'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingJudgmentDebtSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JudgmentNum', models.CharField(max_length=255)),
                ('JudgmentSummary', models.CharField(max_length=255)),
                ('DebtID', models.CharField(max_length=255)),
                ('Name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Role', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('AlternateNames', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('DebtPartyStatus', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('StatusDate', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MissingJudgmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JudgmentNum', models.CharField(max_length=255)),
                ('JudgmentSummary', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('RelatedJudgment', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('DocketNumber', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('VenueId', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('FilingLocation', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Court', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('JudgmentStatus', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('StatusDate', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('JudgmentAmount', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('CourtCosts', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Interest', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('AttorneyFee', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('OtherAmount', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('ProcessingLocation', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('JudgmentEnterDate', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Time', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('JudgmentFilingDate', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MissingJudgmentDocumentSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JudgmentNum', models.CharField(max_length=255)),
                ('JudgmentSummary', models.CharField(max_length=255)),
                ('DebtId', models.CharField(max_length=255)),
                ('DocumentType', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('DocumentFileDate', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('DocumentStatus', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('PartyNameRole1', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('PartyNameRole2', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('PartyNameRole3', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('PartyNameRole4', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MissingJudgmentJudgmentSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JudgmentNum', models.CharField(max_length=255)),
                ('JudgmentSummary', models.CharField(max_length=255)),
                ('DebtID', models.CharField(max_length=255)),
                ('JudgmentAmount', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('JudgmentStatus', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('StatusDate', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('DebtAmount', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('DebtStatus', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('PartyDebtStatus', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('PartyDebtStatusDate', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('PartyInformation', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Role', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('AlternateNames', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('SelfRepresented', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('BirthDate', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Address1', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Address2', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Phone', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Attorney', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('GuardianInformation', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('GuardianAddress1', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('GuardianAddress2', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('AffiliationCode', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('AppointmentDate', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('ReqBondAmount', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('BondReceivedIndicator', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MissingJudgmentParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JudgmentNum', models.CharField(max_length=255)),
                ('JudgmentSummary', models.CharField(max_length=255)),
                ('DebtID', models.CharField(max_length=255)),
                ('DebtStatus', models.CharField(max_length=255)),
                ('DebtAmount', models.CharField(max_length=255)),
                ('AttorneyFee', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Cost', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Interest', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('OtherAmount', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('DebtEnterDate', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
    ]
