# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-31 00:06


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dobscraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scnjdebtordob',
            old_name='case_number',
            new_name='judgment_number',
        ),
    ]
