# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-12-20 20:27


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCDobDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(max_length=255)),
                ('judgment_num', models.CharField(max_length=25)),
                ('party_name', models.CharField(max_length=50)),
                ('party_dob', models.CharField(max_length=25)),
            ],
        ),
    ]
