# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-13 17:09


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_forenames_surnames'),
    ]

    # operations = [
    #     migrations.CreateModel(
    #         name='Forename',
    #         fields=[
    #             ('name', models.CharField(max_length=255)),
    #             ('name_match', models.CharField(max_length=255, primary_key=True, serialize=False)),
    #             ('score', models.DecimalField(decimal_places=0, max_digits=10)),
    #             ('deleted', models.CharField(max_length=1)),
    #             ('nickname', models.CharField(max_length=1)),
    #         ],
    #         options={
    #             'db_table': 'forenames',
    #             'managed': False,
    #         },
    #     ),
    #     migrations.CreateModel(
    #         name='Surname',
    #         fields=[
    #             ('name', models.CharField(max_length=255)),
    #             ('name_match', models.CharField(max_length=255, primary_key=True, serialize=False)),
    #             ('score', models.DecimalField(decimal_places=0, max_digits=10)),
    #             ('deleted', models.CharField(max_length=1)),
    #             ('nickname', models.CharField(max_length=1)),
    #         ],
    #         options={
    #             'db_table': 'surnames',
    #             'managed': False,
    #         },
    #     ),
    # ]
    operations = [
        migrations.RenameModel("Forenames", "Forename"),
        migrations.RenameModel("Surnames", "Surname")
    ]
