# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-05 18:06


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_client_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_method',
            field=models.CharField(choices=[('EM', 'Email'), ('TL', 'Telephone'), ('WB', 'Web Services')], default='EM', max_length=2),
        ),
    ]
