# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-05 18:23


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_order_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchname',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
    ]
