# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-28 02:30


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_searchname_report_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='title_number',
            field=models.CharField(max_length=20, verbose_name='Client file number'),
        ),
    ]
