# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-01 15:56


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20180127_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('file_type', models.CharField(choices=[('PDF', 'pdf')], default='PDF', max_length=10)),
                ('report_type', models.CharField(choices=[('Bankruptcy', 'Bankruptcy'), ('State', 'State'), ('Usdc', 'Usdc'), ('All Reports', 'All Reports')], max_length=50)),
                ('filename', models.CharField(max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
