# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-25 23:35


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_generatedreport_merged_report_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreport',
            name='num_bankruptcy_matches',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='num_state_matches',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='num_usdc_matches',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
