# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-28 20:53


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20180427_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreport',
            name='docket_list_filename',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
