# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-09 17:26


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20180604_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreport',
            name='num_patriot_matches',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='patriot_filename',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
