# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-15 15:08


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_order_is_reorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='internal_tracking_num',
            field=models.CharField(blank=True, max_length=100, verbose_name='Internal number'),
        ),
    ]
