# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-14 20:01


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_order_date_invoiced'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreport',
            name='name_select_ready',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_invoiced',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
